name: Keep Render Bot Alive

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: ⬇️ Checkout mã nguồn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Thiết lập Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 📦 Cài đặt thư viện
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Ping endpoint
        id: ping
        run: |
          # Khởi tạo log file nếu chưa tồn tại
          if [ ! -f ping_log.md ]; then
            echo "| Thời gian | Trạng thái | Chi tiết |" > ping_log.md
            echo "|---|---|---|" >> ping_log.md
          fi
          
          # Thực hiện ping và lưu output
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S')
          PING_OUTPUT=$(python ping.py 2>&1) || true
          
          # Xác định trạng thái từ output
          if echo "$PING_OUTPUT" | grep -q "200 OK"; then
            echo "status=success" >> $GITHUB_OUTPUT
            STATUS="✅ Success"
          else
            echo "status=fail" >> $GITHUB_OUTPUT
            STATUS="❌ Fail"
          fi
          
          # Lưu log
          echo "| $TIMESTAMP | $STATUS | $PING_OUTPUT |" >> ping_log.md
          
          # Giữ 30 log gần nhất
          if [ $(wc -l < ping_log.md) -gt 32 ]; then
            head -n 2 ping_log.md > ping_log.tmp
            tail -n 30 ping_log.md >> ping_log.tmp
            mv ping_log.tmp ping_log.md
          fi

      - name: 📊 Cập nhật thống kê
        run: |
          # Tạo file ngắn gọn cho README
          (head -n 2 ping_log.md && tail -n 30 ping_log.md) > ping_log_short.md
          
          # Tính uptime
          TOTAL=$(grep -c "[✅❌]" ping_log.md)
          if [ $TOTAL -eq 0 ]; then
            echo "0.00" > uptime_percent.txt
          else
            SUCCESS=$(grep -c "✅" ping_log.md)
            awk "BEGIN {printf \"%.2f\", ($SUCCESS/$TOTAL)*100}" > uptime_percent.txt
          fi

      - name: 🟢 Cập nhật badge
        run: |
          if [ "${{ steps.ping.outputs.status }}" = "success" ]; then
            echo "![Uptime](https://img.shields.io/badge/uptime-Online-brightgreen)" > uptime_badge.md
          else
            echo "![Uptime](https://img.shields.io/badge/uptime-Offline-red)" > uptime_badge.md
          fi

      - name: 📈 Vẽ chart
        run: python plot_uptime.py

      - name: 🔄 Cập nhật README
        run: |
          CURRENT_TIME=$(date -u '+%Y-%m-%d %H:%M:%S')
          UPTIME_PERCENT=$(cat uptime_percent.txt)
          LAST_CHECK=$(tail -n 1 ping_log.md | cut -d'|' -f2,3)
          TOTAL_PINGS=$(grep -c "[✅❌]" ping_log.md)

          {
            echo "<div align=\"center\">"
            echo
            echo "# 🚦 Render Service Status"
            echo
            echo "<!--badge-start-->"
            cat uptime_badge.md
            echo "<!--badge-end-->"
            echo
            echo "**Monitoring:** \`telegram-template-bot.onrender.com\`"
            echo
            echo "| Metric | Value |"
            echo "|:--|:--|"
            echo "| ⏰ Last Update | $CURRENT_TIME UTC |"
            echo "| 🔄 Total Pings | $TOTAL_PINGS |"
            echo "| ✅ Uptime (30 lần gần nhất) | $UPTIME_PERCENT% |"
            echo "| ⌛ Ping Interval | 30 phút |"
            echo "| 📡 Last Check |$LAST_CHECK |"
            echo
            echo "</div>"
            echo
            echo "<div align=\"center\">"
            echo
            echo "## 📊 Uptime Chart"
            echo "<br/>"
            echo "<picture>"
            echo "<source media=\"(prefers-color-scheme: dark)\" srcset=\"uptime_chart.png\">"
            echo "<source media=\"(prefers-color-scheme: light)\" srcset=\"uptime_chart.png\">"
            echo "<img alt=\"Uptime Chart\" src=\"uptime_chart.png\" style=\"width: 100%; max-width: 600px; height: auto; margin: 8px auto; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); display: block;\">"
            echo "</picture>"
            echo "<br/>"
            echo
            echo "</div>"
            echo
            echo "<details><summary>📝 Lịch sử Ping (30 lần gần nhất)</summary>"
            echo
            echo "<!--ping-log-start-->"
            cat ping_log_short.md
            echo "<!--ping-log-end-->"
            echo
            echo "</details>"
            echo
            echo "<div align=\"center\">"
            echo
            echo "---"
            echo
            echo "<sub>⚡️ Powered by [telebot-monitor](https://github.com/vhd0/telebot-monitor) | 🕒 Cập nhật mỗi 30 phút</sub>"
            echo
            echo "</div>"
          } > README.md

      - name: 💾 Commit thay đổi
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md ping_log.md uptime_badge.md uptime_chart.png
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Cập nhật uptime [skip ci]" \
              -m "- Thời gian: $(date -u '+%Y-%m-%d %H:%M:%S') UTC" \
              -m "- Status: ${{ steps.ping.outputs.status }}" \
              -m "- Badge & Chart đã cập nhật"
            git pull --rebase origin main
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
