name: Keep Render Bot Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # Chạy mỗi 30 phút
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: ⬇️ Checkout mã nguồn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Thiết lập Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 📦 Cài đặt thư viện
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 🚀 Ping endpoint
        run: |
          if [ ! -f ping_log.md ]; then
            echo "| Thời gian | Trạng thái | Chi tiết |" > ping_log.md
            echo "|---|---|---|" >> ping_log.md
          fi
          
          PING_OUTPUT=$(timeout 90s python ping.py 2>&1 || echo "⏰ Timeout sau 90s")
          
          # Kiểm tra kết quả cuối cùng của ping, bao gồm cả retry thành công
          if echo "$PING_OUTPUT" | grep -q "200 OK.*Khởi động thành công" || echo "$PING_OUTPUT" | grep -q "200 OK.*Phản hồi"; then
            STATUS="✅ Success"
            # Nếu là khởi động thành công, ghi toàn bộ quá trình retry vào chi tiết
            if echo "$PING_OUTPUT" | grep -q "200 OK.*Khởi động thành công"; then
              # Giữ nguyên output để show quá trình retry
              FINAL_OUTPUT="$PING_OUTPUT"
            else
              # Nếu là ping bình thường, chỉ lấy dòng cuối
              FINAL_OUTPUT=$(echo "$PING_OUTPUT" | grep "200 OK")
            fi
          else
            STATUS="❌ Fail"
            # Nếu thất bại, chỉ lấy thông báo lỗi cuối cùng
            FINAL_OUTPUT=$(echo "$PING_OUTPUT" | tail -n 1)
          fi
          
          # Ghi vào log chỉ một lần cho mỗi lần ping
          echo "| $(date -u '+%Y-%m-%d %H:%M:%S') | $STATUS | $FINAL_OUTPUT |" >> ping_log.md
          
          if [ $(wc -l < ping_log.md) -gt 32 ]; then
            head -n 2 ping_log.md > ping_log.tmp
            tail -n 30 ping_log.md >> ping_log.tmp
            mv ping_log.tmp ping_log.md
          fi

      - name: 📊 Cập nhật chart và thống kê
        run: |
          (head -n 2 ping_log.md && tail -n 30 ping_log.md) > ping_log_short.md
          tail -n +3 ping_log.md | tail -n 30 > log_for_chart.txt
          python plot_uptime.py

          TOTAL=$(wc -l < log_for_chart.txt)
          if [ "$TOTAL" -eq 0 ]; then
            UPTIME_PERCENT=0
          else
            # Tính success dựa trên status ✅, không quan tâm số lần retry
            SUCCESS=$(grep -c "✅" log_for_chart.txt)
            UPTIME_PERCENT=$(awk "BEGIN {printf \"%.2f\", ($SUCCESS/$TOTAL)*100}")
          fi
          echo "$UPTIME_PERCENT" > uptime_percent.txt

      - name: 🟢 Tạo badge
        run: |
          # Kiểm tra status dựa trên trạng thái ✅/❌ thay vì nội dung
          LAST_LINE=$(tail -n 1 ping_log.md)
          if echo "$LAST_LINE" | grep -q "✅"; then
            LAST_STATUS="Online"
            COLOR="brightgreen"
          else
            LAST_STATUS="Offline"
            COLOR="red"
          fi
          echo "![Uptime](https://img.shields.io/badge/uptime-$LAST_STATUS-$COLOR)" > uptime_badge.md

      - name: 🔄 Cập nhật README
        run: |
          CURRENT_TIME=$(date -u '+%Y-%m-%d %H:%M:%S')
          TOTAL_PINGS=$(wc -l < log_for_chart.txt)
          UPTIME_PERCENT=$(cat uptime_percent.txt)
          LAST_CHECK=$(tail -n 1 ping_log.md | cut -d'|' -f2,3)

          {
            echo "<div align=\"center\">"
            echo
            echo "# 🚦 Render Service Status"
            echo
            echo "<!--badge-start-->"
            cat uptime_badge.md
            echo "<!--badge-end-->"
            echo
            echo "**Monitoring:** \`telegram-template-bot.onrender.com\`"
            echo
            echo "| Metric | Value |"
            echo "|:--|:--|"
            echo "| ⏰ Last Update | $CURRENT_TIME UTC |"
            echo "| 🔄 Total Pings | $TOTAL_PINGS |"
            echo "| ✅ Uptime (30 lần gần nhất) | $UPTIME_PERCENT% |"
            echo "| ⌛ Ping Interval | 30 phút |"
            echo "| 📡 Last Check |$LAST_CHECK |"
            echo
            echo "</div>"
            echo
            echo "<div align=\"center\">"
            echo
            echo "## 📊 Uptime Chart"
            echo "<br/>"
            echo "<picture>"
            echo "<source media=\"(prefers-color-scheme: dark)\" srcset=\"uptime_chart.png\">"
            echo "<source media=\"(prefers-color-scheme: light)\" srcset=\"uptime_chart.png\">"
            echo "<img alt=\"Uptime Chart\" src=\"uptime_chart.png\" style=\"width: 100%; max-width: 600px; height: auto; margin: 8px auto; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); display: block;\">"
            echo "</picture>"
            echo "<br/>"
            echo
            echo "</div>"
            echo
            echo "<details><summary>📝 Lịch sử Ping (30 lần gần nhất)</summary>"
            echo
            echo "<!--ping-log-start-->"
            cat ping_log_short.md
            echo "<!--ping-log-end-->"
            echo
            echo "</details>"
            echo
            echo "<div align=\"center\">"
            echo
            echo "---"
            echo
            echo "<sub>⚡️ Powered by [telebot-monitor](https://github.com/vhd0/telebot-monitor) | 🕒 Cập nhật mỗi 30 phút</sub>"
            echo
            echo "</div>"
          } > README.md.new

          mv README.md.new README.md

      - name: 💾 Commit thay đổi
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add README.md ping_log.md uptime_badge.md uptime_chart.png

          if ! git diff --staged --quiet; then
            git commit -m "🤖 Cập nhật uptime [skip ci]" -m "- Thời gian: $(date -u '+%Y-%m-%d %H:%M:%S') UTC" -m "- Badge & Chart đã cập nhật" -m "- Log mới đã thêm"
            git pull --rebase origin main
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
